spring:
  application:
    name: 'bot'
  datasource:
    url: jdbc:h2:file:./data/shashla;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update

bot-config:
  bot-token:
  bot-name:
  gc-chat-id:
  personal-chat-id:

logging:
  level:
    root: INFO
  file:
    name: ./logs/application.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7
      total-size-cap: 100MB